export const authActionTypes = {
    SIGN_IN: 'SIGN_IN',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAIL: 'SIGN_IN_FAIL',

    FORGOT_PASSWORD:"FORGOT_PASSWORD",
    FORGOT_PASSWORD_SUCCESS:"FORGOT_PASSWORD_SUCCESS",
    FORGOT_PASSWORD_FAIL:"FORGOT_PASSWORD_FAIL",

    RESET_PASSWORD:"RESET_PASSWORD",
    RESET_PASSWORD_SUCCESS:"RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAIL:"RESET_PASSWORD_FAIL",

    LOGOUT:"LOGOUT"
}


