export const customerActionTypes = {
    GET_CUSTOMERS:'GET_CUSTOMERS',
    GET_CUSTOMERS_SUCCESS:'GET_CUSTOMERS_SUCCESS',
    GET_CUSTOMERS_FAILURE:'GET_CUSTOMERS_FAILURE',

    APPROVE_CUSTOMER:'APPROVE_CUSTOMER',
    APPROVE_CUSTOMER_SUCCESS:'APPROVE_CUSTOMER_SUCCESS',
    APPROVE_CUSTOMER_FAILURE:'APPROVE_CUSTOMER_FAILURE',

    SET_CURRENT_READ:'SET_CURRENT_READ',
    SET_CURRENT_EDIT:'SET_CURRENT_EDIT',
    SET_CURRENT_DELETE:'SET_CURRENT_DELETE',

    SEARCH_CUSTOMER:'SEARCH_CUSTOMER',
    SEARCH_CUSTOMER_SUCCESS:'SEARCH_CUSTOMER_SUCCESS',
    SEARCH_CUSTOMER_FAILURE:'SEARCH_CUSTOMER_FAILURE',

    CREATE_CUSTOMER:'CREATE_CUSTOMER',
    CREATE_CUSTOMER_SUCCESS:'CREATE_CUSTOMER_SUCCESS',
    CREATE_CUSTOMER_FAILURE:'CREATE_CUSTOMER_FAILURE',

    DELETE_CUSTOMER:'DELETE_CUSTOMER',
    DELETE_CUSTOMER_SUCCESS:'DELETE_CUSTOMER_SUCCESS',
    DELETE_CUSTOMER_FAILURE:'DELETE_CUSTOMER_FAILURE',

    
    UPDATE_CUSTOMER:'UPDATE_CUSTOMER',
    UPDATE_CUSTOMER_SUCCESS:'UPDATE_CUSTOMER_SUCCESS',
    UPDATE_CUSTOMER_FAILURE:'UPDATE_CUSTOMER_FAILURE',
}