export const uiActionTypes = {
    OPEN_MODAL:'OPEN_MODAL',
    CLOSE_MODAL:'CLOSE_MODAL',

    OPEN_ADVANCED_BOX:'OPEN_ADVANCED_BOX',
    CLOSE_ADVANCED_BOX:'CLOSE_ADVANCED_BOX',

    OPEN_EDIT_BOX:'OPEN_EDIT_BOX',
    CLOSE_EDIT_BOX:'CLOSE_EDIT_BOX',

    OPEN_PANEL:'OPEN_PANEL',
    CLOSE_PANEL:'CLOSE_PANEL',
    COLLAPSE_PANEL:'COLLAPSE_PANEL',

    OPEN_BOX:'OPEN_BOX',
    CLOSE_BOX:'CLOSE_BOX',
    COLLAPSE_BOX:'COLLAPSE_BOX',

    OPEN_READ_BOX:'OPEN_READ_BOX',
    CLOSE_READ_BOX:'CLOSE_READ_BOX',
    COLLAPSE_READ_BOX:'COLLAPSE_READ_BOX'
}